['eviction_filings_total',
 'eviction_filings_rate',
 'eviction_filings_completed',
 'case_type_single_action',
 'case_type_joint_action',
 'back_rent_median',
 'back_rent_0',
 'back_rent_1_to_999',
 'back_rent_1000_to_2499',
 'back_rent_2500_to_4999',
 'back_rent_5000_or_more',
 'landlord_represented',
 'tenant_represented',
 'tenant_rep_pa',
 'tenant_rep_laa',
 'eviction_order_yes',
 'eviction_order_no',
 'eviction_order_yes_tenant_prose',
 'eviction_order_no_tenant_prose',
 'eviction_order_yes_tenant_represented',
 'eviction_order_no_tenant_represented',
 'eviction_order_yes_tenant_rep_pa',
 'eviction_order_no_tenant_rep_pa',
 'eviction_order_yes_tenant_rep_laa',
 'eviction_order_no_tenant_rep_laa',
 'ftu_eviction_order',
 'ftu_other_outcome',
 'ftu_no_outcome',
 'ftu_eviction_order_tenant_prose',
 'ftu_other_outcome_tenant_prose',
 'ftu_no_outcome_tenant_prose',
 'ftu_eviction_order_tenant_represented',
 'ftu_other_outcome_tenant_represented',
 'ftu_no_outcome_tenant_represented',
 'default_eviction_order_yes',
 'default_eviction_order_no',
 'default_eviction_order_yes_tenant_prose',
 'default_eviction_order_no_tenant_prose',
 'default_eviction_order_yes_tenant_represented',
 'default_eviction_order_no_tenant_represented',
 'housing_units_total',
 'housing_units_rental',
 'housing_units_other',
 'median_rent',
 'population_total',
 'population_poverty_below',
 'population_poverty_above',
 'population_race_white',
 'population_race_black',
 'population_race_latinx',
 'population_race_asian',
 'population_race_other',
 'up_to_middle',
 'not_highschool_grad',
 'high_school_grad',
 'some_college',
 'associate',
 'bachelor',
 'graduate',
 'county',
 'pop_over_25',
 'total_crime',
 'total_crime_class_Less serious offences',
 'total_crime_class_Property Crime',
 'total_crime_class_Violent Crime',
 'total_primary_type_ARSON',
 'total_primary_type_ASSAULT',
 'total_primary_type_BATTERY',
 'total_primary_type_BURGLARY',
 'total_primary_type_CONCEALED CARRY LICENSE VIOLATION',
 'total_primary_type_CRIM SEXUAL ASSAULT',
 'total_primary_type_CRIMINAL DAMAGE',
 'total_primary_type_CRIMINAL TRESPASS',
 'total_primary_type_DECEPTIVE PRACTICE',
 'total_primary_type_GAMBLING',
 'total_primary_type_HOMICIDE',
 'total_primary_type_HUMAN TRAFFICKING',
 'total_primary_type_INTERFERENCE WITH PUBLIC OFFICER',
 'total_primary_type_INTIMIDATION',
 'total_primary_type_KIDNAPPING',
 'total_primary_type_LIQUOR LAW VIOLATION',
 'total_primary_type_MOTOR VEHICLE THEFT',
 'total_primary_type_NARCOTICS',
 'total_primary_type_NON - CRIMINAL',
 'total_primary_type_NON-CRIMINAL',
 'total_primary_type_NON-CRIMINAL (SUBJECT SPECIFIED)',
 'total_primary_type_OBSCENITY',
 'total_primary_type_OFFENSE INVOLVING CHILDREN',
 'total_primary_type_OTHER NARCOTIC VIOLATION',
 'total_primary_type_OTHER OFFENSE',
 'total_primary_type_PROSTITUTION',
 'total_primary_type_PUBLIC INDECENCY',
 'total_primary_type_PUBLIC PEACE VIOLATION',
 'total_primary_type_ROBBERY',
 'total_primary_type_SEX OFFENSE',
 'total_primary_type_STALKING',
 'total_primary_type_THEFT',
 'total_primary_type_WEAPONS VIOLATION',
 'total_domestic_0',
 'total_domestic_1',
 'total_arrest_0',
 'total_arrest_1',
 'perc_total_crime_class_Less serious offences',
 'perc_total_crime_class_Property Crime',
 'perc_total_crime_class_Violent Crime',
 'perc_increase_total_crime',
 'perc_increase_total_crime_class_Less serious offences',
 'perc_increase_total_crime_class_Property Crime',
 'perc_increase_total_crime_class_Violent Crime',
 'total_building_violations',
 'total_violation_status_COMPLIED',
 'total_violation_status_NO ENTRY',
 'total_violation_status_OPEN',
 'total_inspection_category_COMPLAINT',
 'total_inspection_category_PERIODIC',
 'total_inspection_category_PERMIT',
 'total_inspection_category_REGISTRATION',
 'total_department_bureau_BOILER',
 'total_department_bureau_CONSERVATION',
 'total_department_bureau_CONSTRUCTION EQUIPMENT',
 'total_department_bureau_DEMOLITION',
 'total_department_bureau_ELECTRICAL',
 'total_department_bureau_ELEVATOR',
 'total_department_bureau_IRON',
 'total_department_bureau_NEW CONSTRUCTION',
 'total_department_bureau_PLUMBING',
 'total_department_bureau_REFRIGERATION',
 'total_department_bureau_SIGNS',
 'total_department_bureau_SPECIAL INSPECTION PROGRAM',
 'total_department_bureau_SPECIAL TASK FORCE',
 'total_department_bureau_VENTILATION',
 'total_department_bureau_WATER',
 'total_violation_status_COMPLIED_perc',
 'total_violation_status_NO ENTRY_perc',
 'total_violation_status_OPEN_perc',
 'total_inspection_category_COMPLAINT_perc',
 'perc_increase_bv',
 'commarea',
 'eviction_filings_total_mean_by_commarea',
 'eviction_filings_rate_mean_by_commarea',
 'eviction_filings_completed_mean_by_commarea',
 'case_type_single_action_mean_by_commarea',
 'case_type_joint_action_mean_by_commarea',
 'back_rent_median_mean_by_commarea',
 'back_rent_0_mean_by_commarea',
 'back_rent_1_to_999_mean_by_commarea',
 'back_rent_1000_to_2499_mean_by_commarea',
 'back_rent_2500_to_4999_mean_by_commarea',
 'back_rent_5000_or_more_mean_by_commarea',
 'landlord_represented_mean_by_commarea',
 'tenant_represented_mean_by_commarea',
 'tenant_rep_pa_mean_by_commarea',
 'tenant_rep_laa_mean_by_commarea',
 'eviction_order_yes_mean_by_commarea',
 'eviction_order_no_mean_by_commarea',
 'eviction_order_yes_tenant_prose_mean_by_commarea',
 'eviction_order_no_tenant_prose_mean_by_commarea',
 'eviction_order_yes_tenant_represented_mean_by_commarea',
 'eviction_order_no_tenant_represented_mean_by_commarea',
 'eviction_order_yes_tenant_rep_pa_mean_by_commarea',
 'eviction_order_no_tenant_rep_pa_mean_by_commarea',
 'eviction_order_yes_tenant_rep_laa_mean_by_commarea',
 'eviction_order_no_tenant_rep_laa_mean_by_commarea',
 'ftu_eviction_order_mean_by_commarea',
 'ftu_other_outcome_mean_by_commarea',
 'ftu_no_outcome_mean_by_commarea',
 'ftu_eviction_order_tenant_prose_mean_by_commarea',
 'ftu_other_outcome_tenant_prose_mean_by_commarea',
 'ftu_no_outcome_tenant_prose_mean_by_commarea',
 'ftu_eviction_order_tenant_represented_mean_by_commarea',
 'ftu_other_outcome_tenant_represented_mean_by_commarea',
 'ftu_no_outcome_tenant_represented_mean_by_commarea',
 'default_eviction_order_yes_mean_by_commarea',
 'default_eviction_order_no_mean_by_commarea',
 'default_eviction_order_yes_tenant_prose_mean_by_commarea',
 'default_eviction_order_no_tenant_prose_mean_by_commarea',
 'default_eviction_order_yes_tenant_represented_mean_by_commarea',
 'default_eviction_order_no_tenant_represented_mean_by_commarea',
 'housing_units_total_mean_by_commarea',
 'housing_units_rental_mean_by_commarea',
 'housing_units_other_mean_by_commarea',
 'median_rent_mean_by_commarea',
 'population_total_mean_by_commarea',
 'population_poverty_below_mean_by_commarea',
 'population_poverty_above_mean_by_commarea',
 'population_race_white_mean_by_commarea',
 'population_race_black_mean_by_commarea',
 'population_race_latinx_mean_by_commarea',
 'population_race_asian_mean_by_commarea',
 'population_race_other_mean_by_commarea',
 'up_to_middle_mean_by_commarea',
 'not_highschool_grad_mean_by_commarea',
 'high_school_grad_mean_by_commarea',
 'some_college_mean_by_commarea',
 'associate_mean_by_commarea',
 'bachelor_mean_by_commarea',
 'graduate_mean_by_commarea',
 'county_mean_by_commarea',
 'pop_over_25_mean_by_commarea',
 'total_crime_mean_by_commarea',
 'total_crime_class_Less serious offences_mean_by_commarea',
 'total_crime_class_Property Crime_mean_by_commarea',
 'total_crime_class_Violent Crime_mean_by_commarea',
 'total_primary_type_ARSON_mean_by_commarea',
 'total_primary_type_ASSAULT_mean_by_commarea',
 'total_primary_type_BATTERY_mean_by_commarea',
 'total_primary_type_BURGLARY_mean_by_commarea',
 'total_primary_type_CONCEALED CARRY LICENSE VIOLATION_mean_by_commarea',
 'total_primary_type_CRIM SEXUAL ASSAULT_mean_by_commarea',
 'total_primary_type_CRIMINAL DAMAGE_mean_by_commarea',
 'total_primary_type_CRIMINAL TRESPASS_mean_by_commarea',
 'total_primary_type_DECEPTIVE PRACTICE_mean_by_commarea',
 'total_primary_type_GAMBLING_mean_by_commarea',
 'total_primary_type_HOMICIDE_mean_by_commarea',
 'total_primary_type_HUMAN TRAFFICKING_mean_by_commarea',
 'total_primary_type_INTERFERENCE WITH PUBLIC OFFICER_mean_by_commarea',
 'total_primary_type_INTIMIDATION_mean_by_commarea',
 'total_primary_type_KIDNAPPING_mean_by_commarea',
 'total_primary_type_LIQUOR LAW VIOLATION_mean_by_commarea',
 'total_primary_type_MOTOR VEHICLE THEFT_mean_by_commarea',
 'total_primary_type_NARCOTICS_mean_by_commarea',
 'total_primary_type_NON - CRIMINAL_mean_by_commarea',
 'total_primary_type_NON-CRIMINAL_mean_by_commarea',
 'total_primary_type_NON-CRIMINAL (SUBJECT SPECIFIED)_mean_by_commarea',
 'total_primary_type_OBSCENITY_mean_by_commarea',
 'total_primary_type_OFFENSE INVOLVING CHILDREN_mean_by_commarea',
 'total_primary_type_OTHER NARCOTIC VIOLATION_mean_by_commarea',
 'total_primary_type_OTHER OFFENSE_mean_by_commarea',
 'total_primary_type_PROSTITUTION_mean_by_commarea',
 'total_primary_type_PUBLIC INDECENCY_mean_by_commarea',
 'total_primary_type_PUBLIC PEACE VIOLATION_mean_by_commarea',
 'total_primary_type_ROBBERY_mean_by_commarea',
 'total_primary_type_SEX OFFENSE_mean_by_commarea',
 'total_primary_type_STALKING_mean_by_commarea',
 'total_primary_type_THEFT_mean_by_commarea',
 'total_primary_type_WEAPONS VIOLATION_mean_by_commarea',
 'total_domestic_0_mean_by_commarea',
 'total_domestic_1_mean_by_commarea',
 'total_arrest_0_mean_by_commarea',
 'total_arrest_1_mean_by_commarea',
 'perc_total_crime_class_Less serious offences_mean_by_commarea',
 'perc_total_crime_class_Property Crime_mean_by_commarea',
 'perc_total_crime_class_Violent Crime_mean_by_commarea',
 'perc_increase_total_crime_mean_by_commarea',
 'perc_increase_total_crime_class_Less serious offences_mean_by_commarea',
 'perc_increase_total_crime_class_Property Crime_mean_by_commarea',
 'perc_increase_total_crime_class_Violent Crime_mean_by_commarea',
 'total_building_violations_mean_by_commarea',
 'total_violation_status_COMPLIED_mean_by_commarea',
 'total_violation_status_NO ENTRY_mean_by_commarea',
 'total_violation_status_OPEN_mean_by_commarea',
 'total_inspection_category_COMPLAINT_mean_by_commarea',
 'total_inspection_category_PERIODIC_mean_by_commarea',
 'total_inspection_category_PERMIT_mean_by_commarea',
 'total_inspection_category_REGISTRATION_mean_by_commarea',
 'total_department_bureau_BOILER_mean_by_commarea',
 'total_department_bureau_CONSERVATION_mean_by_commarea',
 'total_department_bureau_CONSTRUCTION EQUIPMENT_mean_by_commarea',
 'total_department_bureau_DEMOLITION_mean_by_commarea',
 'total_department_bureau_ELECTRICAL_mean_by_commarea',
 'total_department_bureau_ELEVATOR_mean_by_commarea',
 'total_department_bureau_IRON_mean_by_commarea',
 'total_department_bureau_NEW CONSTRUCTION_mean_by_commarea',
 'total_department_bureau_PLUMBING_mean_by_commarea',
 'total_department_bureau_REFRIGERATION_mean_by_commarea',
 'total_department_bureau_SIGNS_mean_by_commarea',
 'total_department_bureau_SPECIAL INSPECTION PROGRAM_mean_by_commarea',
 'total_department_bureau_SPECIAL TASK FORCE_mean_by_commarea',
 'total_department_bureau_VENTILATION_mean_by_commarea',
 'total_department_bureau_WATER_mean_by_commarea',
 'total_violation_status_COMPLIED_perc_mean_by_commarea',
 'total_violation_status_NO ENTRY_perc_mean_by_commarea',
 'total_violation_status_OPEN_perc_mean_by_commarea',
 'total_inspection_category_COMPLAINT_perc_mean_by_commarea',
 'perc_increase_bv_mean_by_commarea']